 name: Laravel

 on:
   pull_request:
    branches:
      - production
      
   push:
     branches:
       - production
       
 jobs:
  deploy-to-test:
 
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to test
      uses: appleboy/ssh-action@v0.1.4
      with:
          host: 68.183.88.222
          username: root      
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /var/www/strapi_prod && ./server_deploy.sh'
# #       uses: easingthemes/ssh-deploy@v2.2.11
#       uses: appleboy/ssh-action@v0.1.3
#       env:
#                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#                username: root
#                host: 68.183.88.222      
#                script: 'cd /var/www/strapi_prod && ./server_deploy.sh'
         
